[package]
name = "yew-todo-app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
strum = "0.19"
strum_macros = "0.19"
serde = "1"
serde_derive = "1"
